version: '3'
services:
  vivo-service:
    build:
      context: service
      dockerfile: Dockerfile
    ports:
      - "9000:24224"
      - "9010:9880"
      - "2025:2025"
  vivo-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    depends_on:
      - vivo-service

